grails:
  server:
    port: 8080

dataSource:
  default:
    dbCreate: update  # 'create', 'update', 'none', etc.
    url: jdbc:mysql://mysql:3306/meu_banco  # Conexão com o serviço MySQL no Docker Compose
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: exemploSenha

hibernate:
  cache:
    queries: false

spring:
  datasource:
    hikari:
      poolName: HikariCP
      maximumPoolSize: 10
      
grails:
  plugin:
    liquibase:
      changelog: classpath:db/changelog/db.changelog-master.xml  # Caminho do changelog
      runOnStart: true  # Execute migrações automaticamente ao iniciar
